[package]
name = "colors-fltk"
version = "0.1.0"
edition = "2021"

[dependencies]
mouse-rs = { git = "https://github.com/AltF02/mouse-rs" }
x11-screenshot = "0.2.1"
fltk = "1.2.22"
clipboard-ext = "0.2.0"
